Repository systopia/de.systopia.civioffice, pull requests merged in 2025-02, with the labels that each got.

#76 Define setting data type correctly for "civioffice_renderers" setting
  CRM/Civioffice/Upgrader.php
  settings/civioffice.setting.php
Labels: bug, status:reviewed and tested

#81 Add a note about Composer dependencies in the installation docs
  docs/installation.md
Labels: documentation

#82 Remove access to undefined property in case task form
  CRM/Civioffice/Form/Task/CreateCaseDocuments.php
Labels: bug, status:reviewed and tested

#78 Replace tokens in headers and footers, too
  CRM/Civioffice/DocumentRendererType/LocalUnoconv.php
  Civi/Civioffice/PhpWord/PhpWordTemplateProcessor.php
  Civi/Civioffice/PhpWord/PhpWordTokenReplacer.php
  Civi/Civioffice/PhpWord/Util/TemplateUtil.php
  tests/phpunit/Civi/Civioffice/PhpWord/PhpWordTemplateProcessorTest.php
  tests/phpunit/Civi/Civioffice/PhpWord/TestablePhpWordTemplateProcessor.php
Labels: enhancement, status:needs review

#68 Fix redirect htmlized and failing to load on WordPress
  Civi/Civioffice/Render/Queue/RenderQueueRunner.php
Labels: bug, status:reviewed and tested, needs funding
